USE master
GO

/*
Database Creation Script
©Nathan Motyl
http://nmotyl.github.io/
*/

PRINT 'Creating SSIS_LoggingDB database'
GO

CREATE DATABASE [SSIS_LoggingDB]
 ON  PRIMARY 
( NAME = N'SSIS_LoggingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SSIS_LoggingDB.mdf' , SIZE = 2048MB , MAXSIZE = UNLIMITED, FILEGROWTH = 512MB )
 LOG ON 
( NAME = N'SSIS_LoggingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQL2014\MSSQL\DATA\SSIS_LoggingDB_log.ldf' , SIZE = 512MB , MAXSIZE = UNLIMITED, FILEGROWTH = 128MB )
GO
ALTER DATABASE [SSIS_LoggingDB] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [SSIS_LoggingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [SSIS_LoggingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SSIS_LoggingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SSIS_LoggingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SSIS_LoggingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SSIS_LoggingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SSIS_LoggingDB] SET  READ_WRITE 
GO
ALTER DATABASE [SSIS_LoggingDB] SET RECOVERY FULL 
GO
ALTER DATABASE [SSIS_LoggingDB] SET  MULTI_USER 
GO
ALTER DATABASE [SSIS_LoggingDB] SET PAGE_VERIFY CHECKSUM  
GO
USE [SSIS_LoggingDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SSIS_LoggingDB] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
